# Generated by Django 4.2.3 on 2025-01-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Groceries", "Groceries"),
                            ("Healthcare", "Healthcare"),
                            ("Entertainment", "Entertainment"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Revenue", "Revenue"), ("Expense", "Expense")],
                        default="Expense",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "expenses",
            },
        ),
    ]
